// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wabxwzeijdlvnjlmjvmu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndhYnh3emVpamRsdm5qbG1qdm11Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUwNDE1MjAsImV4cCI6MjA5MDYxNzUyMH0.kY-zKVFD9fykEH6WmjYmBAS4F4UB5FXy1z_wUxZhBQ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});